/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ExerciseDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Exercises`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/oauth-native-callback`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentCard`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentExercises`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentExercisesShow`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentOnboarding`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentOnboardingButton`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentOnboardingCard`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentsList`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentTraining`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentTrainingShow`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ExerciseDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/Exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/oauth-native-callback`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentCard`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentExercises`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentExercisesShow`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentOnboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentOnboardingButton`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentOnboardingCard`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentsList`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentTraining`; params?: Router.UnknownOutputParams; } | { pathname: `/Students/StudentTrainingShow`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ExerciseDetails${`?${string}` | `#${string}` | ''}` | `/Exercises${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/oauth-native-callback${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Settings${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `/Students/StudentCard${`?${string}` | `#${string}` | ''}` | `/Students/StudentExercises${`?${string}` | `#${string}` | ''}` | `/Students/StudentExercisesShow${`?${string}` | `#${string}` | ''}` | `/Students/StudentOnboarding${`?${string}` | `#${string}` | ''}` | `/Students/StudentOnboardingButton${`?${string}` | `#${string}` | ''}` | `/Students/StudentOnboardingCard${`?${string}` | `#${string}` | ''}` | `/Students/StudentsList${`?${string}` | `#${string}` | ''}` | `/Students/StudentTraining${`?${string}` | `#${string}` | ''}` | `/Students/StudentTrainingShow${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ExerciseDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Exercises`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/oauth-native-callback`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentCard`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentExercises`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentExercisesShow`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentOnboarding`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentOnboardingButton`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentOnboardingCard`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentsList`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentTraining`; params?: Router.UnknownInputParams; } | { pathname: `/Students/StudentTrainingShow`; params?: Router.UnknownInputParams; };
    }
  }
}
